cask_args appdir: '/Applications'

# Install Binaries
brew 'awscli'
brew 'azure-cli'
brew 'bitrise'
brew 'gauge'
brew 'git'
brew 'gpg-suite'
brew 'mercurial'
brew 'openssl'
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'

# Development
brew 'go'
brew 'mongodb'
brew 'nvm'
brew 'postgresql'
brew 'python'
brew 'rbenv'
brew 'redis'

# Apps
cask '1password'
cask 'alfred'
cask 'charles'
cask 'docker'
cask 'dotnet'
cask 'dropbox'
cask 'fastlane'
cask 'firefox'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'intellij-idea'
cask 'iterm2'
cask 'java'
cask 'postbox'
cask 'powershell'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'vlc'
